name: hpcore
description: Task management app for HPC

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.4.2
  logger: ^2.3.0
  english_words: ^4.0.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
